### ISSUE TITLE
"COM port unavailable" error on restarting a test

### ISSUE THREAD

**Issue by hmparanjape** [beamteamco/M10-Testware#1]
**To reproduce the issue:**
1. Start a test with GUI and abort it, either by clicking "Stop" in the GUI or by hitting Ctrl+C in the Matlab command window.
2. Restart the test from the GUI.
3. An error will show up in the command window about COM5 not being available (for axial test).

**Potential reason:**

When a test is aborted, the COM5 port is not closed by MATLAB.

**Potential fix:**

At the start of new test, first close all open ports.
`clear(instrfind)`

**Comment by apetersen0** [comment]
Port closing function was missing in the error checking code within sequence execution function. I redesigned the function flow to attempt to close connection before running the sequence. This should have fixed the issue.
